/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#242a33",
        "surface-dim": "#0e141c",
        "on-secondary": "#382f1f",
        "on-tertiary": "#2f3038",
        "tertiary-fixed": "#e2e1ec",
        "on-error": "#690005",
        "on-tertiary-container": "#282931",
        "primary-fixed-dim": "#d2c5b3",
        "surface-variant": "#2f353e",
        "on-primary-fixed-variant": "#4e4638",
        "on-secondary-fixed-variant": "#4f4634",
        "secondary-fixed": "#f0e1c8",
        "primary-container": "#9a8f7f",
        "tertiary": "#c6c5d0",
        "outline": "#979086",
        "outline-variant": "#4c463e",
        "tertiary-fixed-dim": "#c6c5d0",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "on-primary-container": "#30291d",
        "on-primary": "#372f23",
        "surface": "#0e141c",
        "surface-bright": "#343a43",
        "on-secondary-fixed": "#221b0b",
        "on-primary-fixed": "#211b0f",
        "inverse-primary": "#675d4f",
        "tertiary-container": "#90909a",
        "secondary-fixed-dim": "#d3c5ad",
        "surface-container-highest": "#2f353e",
        "surface-container-low": "#161c25",
        "inverse-surface": "#dde3ef",
        "on-secondary-container": "#c5b7a0",
        "background": "#0e141c",
        "surface-tint": "#d2c5b3",
        "on-error-container": "#ffdad6",
        "on-background": "#dde3ef",
        "primary": "#d2c5b3",
        "secondary": "#d3c5ad",
        "on-tertiary-fixed": "#1a1b23",
        "secondary-container": "#524836",
        "primary-fixed": "#eee1ce",
        "surface-container-lowest": "#080f17",
        "on-surface-variant": "#cec5bb",
        "inverse-on-surface": "#2b313a",
        "on-surface": "#dde3ef",
        "surface-container": "#1a2029",
        "on-tertiary-fixed-variant": "#45464f"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [],
}
